feature: Create InputTrader Servlet for Controller
cs-kmitl-2017/group2 pull request #10
Opened 2017-12-08 06:33 UTC by iThanathat

สร้าง Servlet ที่ใช้เรียกหน้าPage JSP ครับ
ขออภัยในที่นี้ เพราะผมยังไม่รู้จะเริ่มเขียนControllerยังไง เลยไปลองหาในอินเตอร์เน็ตดู
ส่วนการเก็บข้อมูลจาก JSP ยังไม่ได้ทำนะครับ ถ้าเกิดหาวิธีได้แล้วจะมาแก้ต่อไป

2017-12-08 10:13 UTC, champillon requested changes
ทำไม PR เหมือนอันที่แล้วอ่ะครับ มีแค่ controller เติมมา จะเอา PR ตัวไหนครับ จะได้ตรวจให้ได้ถูก

2017-12-08 10:13 UTC, champillon commented on src/main/ETDAapp/src/java/th/ac/kmitl/science/comsci/example/controller/InputTrader.java
> +    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
comment นี้ ไว้ทำไรครับ? ถ้าไม่ใช่ทำอะไรก็ลบทิ้งดีกว่าครับ จะได้ไม่สับสนในอนาคต

2017-12-08 10:20 UTC, iThanathat commented
เป็นPRนี้อันเดียวเลยครับๆ
flowตอนนี้คือ เปิดมาจะเป็นหน้าIndex แล้วให้กดลิ้งเข้าไปเพื่อเรียกServlet InputTrader
แล้วก็จะแสดงหน้ากรอกข้อมูลของผู้ซื้อและผู้ขายครับ
![index](https://user-images.githubusercontent.com/26056177/33761554-0e0a610c-dc3c-11e7-8436-2b0610fe98a5.jpg)
![inputseller](https://user-images.githubusercontent.com/26056177/33761559-0f92d57c-dc3c-11e7-94d1-9362d77c3544.jpg)

2017-12-08 10:42 UTC, champillon commented
@iThanathat แล้วรายการสินค้า จะใส่ตรงไหนครับ?

2017-12-08 10:48 UTC, iThanathat commented
ยังไม่ได้ใส่Fieldตรงนั้นเพิ่มลงไปครับ ตอนนี้เลยทำแค่เท่าที่มีModelไปก่อน

2017-12-08 10:51 UTC, champillon requested changes
ฝากแก้ไขด้วยนะครับ

2017-12-08 10:51 UTC, champillon commented on src/main/ETDAapp/src/java/th/ac/kmitl/science/comsci/example/controller/InputTrader.java
> +    }// </editor-fold>
ทำไมยังมี comment หล่ะครับ

2017-12-08 10:51 UTC, champillon commented on src/main/ETDAapp/web/view/buyerPage.jsp
> +
ทำไมบรรทัดนี้มีเว้นด้วยหล่ะครับ

2017-12-08 10:51 UTC, champillon commented on src/main/ETDAapp/src/java/th/ac/kmitl/science/comsci/example/controller/InputTrader.java
> +
ทำไมเว้นบรรทัดครับ

2017-12-08 13:52 UTC, thebankky requested changes
แก้ไขด้วยครับ

2017-12-08 13:52 UTC, Thel3ankky commented on src/main/ETDAapp/web/view/buyerPage.jsp
> +        <h2>ขอ้มูลของผู้ซื้อ</h2>
พิมพ์​ผิดนะครับ

2017-12-08 13:52 UTC, Thel3ankky commented on src/main/ETDAapp/web/view/buyerPage.jsp
> +        <title>JSP Page</title>
ไฟล์ชื่อ buyerPage  ทำไมtitle เป็น JSP Page หล่ะครับ

2017-12-08 13:52 UTC, Thel3ankky commented on src/main/ETDAapp/web/view/sellerPage.jsp
> +        <title>ใบกำกับภาษีสำหรับผู้ขาย</title>
title จะเอาภาษาไทยหรืออังกฤษครับ? 2หน้าข้างบนใช้ภาษาอังกฤษ อีก 2 หน้าภาษาไทย

2017-12-08 14:07 UTC, Thel3ankky commented on src/main/ETDAapp/web/index.jsp
> +        <title>TaxInvoice</title>
ตรงนี้จะเอาเป็นภาษาอังกฤษ​แบบนี้ใช่ไหมครับ?

2017-12-08 14:15 UTC, iThanathat commented on src/main/ETDAapp/web/index.jsp
> +        <title>TaxInvoice</title>
อ่อ โอเคครับ เดี๋ยวผมแก้ให้อีกที ขออภัยครับ

2017-12-08 14:30 UTC, champillon approved these changes
LGTM la

2017-12-09 13:30 UTC, iThanathat commented
@Thel3ankky พี่ไม่ได้ลืมPRนี้ใช่ไหมครับ T_T แก้ให้ตามที่บอกแล้วครับ ช่วยมาApproveให้ผมที  TAT

2017-12-09 13:31 UTC, champillon commented
@iThanathat merge ให้เลย @Thel3ankky ช้าาาาาา

2017-12-09 13:31 UTC, merged

2017-12-09 13:33 UTC, iThanathat commented
เอาอย่างงั้นเลยนะฮะ 55555 ขอบคุณมากครับ 👍

2017-12-09 13:38 UTC, champillon commented
ไปตัดคะแนน @Thel3ankky  แทน ถถถถถถถถถถถถ