feature: Create Seller model
cs-kmitl-2017/group2 pull request #6
Opened 2017-11-26 08:48 UTC by iThanathat

2017-11-27 00:50 UTC, champillon requested changes
Kindly describe how you manage the address

2017-11-27 00:50 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +
remove duplicated blank line

2017-11-27 00:50 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/SellerTest.java
> +        Seller seller = new Seller();
Add one blank line to separate declaration point, processing point and validation (or return) point

2017-11-27 10:47 UTC, iThanathat commented
I think about create an Address class for both Buyer and Seller to use.
Sorry for a late reply.I have an exam on this week. I will try to reslove problem as much as I can. Thank you :)

2017-11-27 13:59 UTC, champillon requested changes
Please fix the code due to tge comments.
It’s ok for late reply, we do it asynchronous way.

2017-11-27 13:59 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +public class Seller{
Put the space between Seller and “{“

2017-11-27 17:40 UTC, champillon approved these changes
This PR is LGTM, let me ask another.
You need 3 LGTMs to merge this PR.

2017-11-28 02:28 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/SellerTest.java
> +        Assert.assertEquals(seller.getId(),id);
Please add one space after every comma krub
Referred to: 

> With a computer, use only one space following periods, commas, semicolons, colons, exclamation points, question marks, and quotation marks. The space needed after these punctuation marks is proportioned automatically.

2017-11-28 02:33 UTC, Thel3ankky commented
This one LGTM

2017-11-28 02:34 UTC, thebankky approved these changes
This one LGTM

2017-11-28 02:43 UTC, khemtat approved these changes
The changes look fine, also LGTM krub.

2017-11-28 02:46 UTC, thebankky approved these changes
LGTM

2017-11-29 05:09 UTC, merged

2017-11-29 05:15 UTC, champillon commented
ตัดคะแนนดังนี้
1. design as components => ทำไมไม่ group Seller กับ Buyer เป็น class เดียวกัน เพราะ Data Structure เหมือนกัน (ตัดไป 0.5 คะแนน)
2. naming & convention => ทีม reviewer ต้อง comments เรื่อง spacing และยังแก้ไม่ครบ เช่น method parameter ยังติดกับ "," อยู่
3. technology leveraging => ยังไม่ได้ใช้ tech อะไรยากครับ ไม่มีคะแนนให้
4. git usage => ใน PR ไม่มีรายละเอียด งานที่ทำ จึงต้องถามว่าจะ design ยังไง และ commit log ยังไม่สื่อครับ

แต่พยายามได้ดีมากครับ สู้ๆ