feature: Create Address model
cs-kmitl-2017/group2 pull request #7
Opened 2017-11-28 15:46 UTC by iThanathat

I plan to create Address for SellerAddress and BuyerAddress to inherit later on.
Feel free to give me any advice or idea, and I will improve myself to be better than this.
Thank you.

2017-11-28 15:51 UTC, iThanathat commented
More question : 
Why does it has to have 1stLineAddress and 2ndLineAddress when the the other line also have all info about address? Just for my curioisity ^^

2017-11-29 05:25 UTC, champillon commented
@iThanathat I do also comment on this field duplication too somehow it's the government standard, must follow ETDA ...

2017-11-30 02:55 UTC, champillon commented
@iThanathat ขอ link หน่อยครับ ว่าเอา field ในที่อยู่มาจากไหนครับ จะได้ review ได้

2017-11-30 05:14 UTC, iThanathat commented
@champillon link ยังไงอ่ะครับ เป็น input ของ ที่อยู่หรือยังไง

2017-11-30 06:46 UTC, champillon commented
@iThanathat field ที่เอามาทำเป็น PR นี้ เอามาจากเอกสารหน้าไหน อะไรแบบนี้อ่ะครับ

2017-11-30 10:49 UTC, iThanathat commented
@champillon  เอามาจากเอกสารหน้า10-11 ของเอกสารETDA ในส่วนที่เป็นที่อยู่ของผู้ขายและผู้ซื้อครับ แต่ยังไม่มีส่วนที่เป็น City ,Country ,Sub Countryครับ

2017-11-30 12:21 UTC, khemtat commented
หลักการระบุ city, country และ sub-country 

ดูได้จากเอกสาร ขมธอ. 3-2560 ข้อ 8.7-8.10 ครับ

2017-12-01 04:12 UTC, champillon commented
@iThanathat พี่ดูแล้วไม่มี field alley นะ
อันนี้เราจะสื่อสารกะเพื่อนในทีมยังไงดีอ่ะ

<img width="728" alt="screen shot 2560-12-01 at 11 08 26" src="https://user-images.githubusercontent.com/1620789/33467597-29ed36ce-d688-11e7-866f-28b1c4543c75.png">

2017-12-01 04:50 UTC, iThanathat commented
@champillon อ้อ ผมแปลคำว่าซอยเป็นalley เพราะผมไม่รู้จะใช้คำว่าอะไรแทนตัวแปลซอยดี ก็เลยใช่alleyแทนครับผม

2017-12-02 03:41 UTC, champillon commented
@iThanathat เราว่ากลับไปใช้ LineOne, ... ดีมั้ย เพราะไม่งั้น village กับ villageNo นี่มันจะสับสนมาก ทั้งๆที่จริงๆมันเป็นหมู่บ้าน กะหมู่ที่

เราเข้าใจ นายพยายามทำให้เพื่อนๆเข้าใจ component ของนายง่ายขึ้นด้วยการตั้งชื่อโดยไม่ต้องไปอ่านเอกสาร ETDA แต่เราที่อยู่ที่ละเอียดอ่อนมากเพราะไม่มี feild ที่ใช้เฉพาะ แล้วจะยิ่งสับสนมากอย่างตัวอย่างด้านบน

ดังนั้น ถ้าการตั้งชื่อให้ง่าย เพื่อเพื่อนไม่ต้องอ่านเอกสาร ETDA เป็นไปไม่ได้ ก็ต้องทำให้มันยากขึ้นแต่เข้าใจตรงกันโดยอิงตามชื่อในเอกสาร ETDA ดีกว่าครับ เพราะทุกคนจะได้อิงเอกสารเดียวกัน และไม่สับสน

2017-12-02 03:44 UTC, champillon requested changes
ฝากดูแล้วแก้ตามนี้ด้วยครับ

2017-12-02 03:44 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +package th.ac.kmitl.science.comsci.example.models;
ทำไมมีไฟล์นี้มาด้วยหล่ะครับ ซ้ำกับ PR เดิมที่ merge ไปแล้วและอยู่ใน master รึป่าว

2017-12-02 03:44 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/AddressTest.java
> +        String firstLineAddress = "Some 1stLineAddress";
ใส่ข้อมูล test ให้เหมาะสม และใช้ข้อมูลจริงครับ อาจจะใช้ข้อมูลที่อยู่ในตัวละครก็ได้ เช่น project เก่าๆพี่ mock เป็น Avenger ครับ

2017-12-02 03:44 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/SellerTest.java
> +public class SellerTest {
อันนี้ซ้ำกับ code ใน branch master นะครับ

2017-12-02 09:25 UTC, iThanathat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +package th.ac.kmitl.science.comsci.example.models;
@champillon อันนี้ผมน่าจะaddผิดไฟล์มาครับ ขออภัยด้วยครับ

2017-12-02 10:42 UTC, champillon requested changes
เอาไฟล์ Seller กับ SellerTest ออกด้วยครับ

2017-12-02 10:42 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +package th.ac.kmitl.science.comsci.example.models;
เอาไฟล์ออกด้วยครับ

2017-12-02 10:55 UTC, iThanathat commented
ขอโทษทีครับ พอดีก่อนหน้านี้ ผมลืมFetch แล้ว Mergeใหม่ มันเลยยังมีของเก่าส่งไปด้วยครับ

2017-12-02 11:59 UTC, champillon approved these changes
LGTM la

2017-12-02 12:28 UTC, khemtat approved these changes
The changes are LGTM krub.

2017-12-03 01:29 UTC, merged

2017-12-03 01:50 UTC, champillon commented
ตัดคะแนนดังนี้

1. design as components (1 คะแนน) => ยังไม่ให้เต็ม 2 คะแนน แต่ดีแล้วที่ทำ Address ให้ใช้ได้ทั้ง Buyer และ Seller แต่มันยังเป็นแค่ composition ง่ายๆ อยากให้มีการ design อะไรที่ยากกว่านี้ ถึงจะให้เต็ม 2 คะแนน

2. naming & convention (0.75 คะแนน) => ตอนแรกตั้งชื่อตัวแปรมา ทำให้เพื่อนอ่านยากและเข้าใจยาก เช่น villege กับ villegeNo (หมู่บ้าน กับหมู่ที่) เลยตัดไป 0.25 คะแนน
(นักบอลที่ดี ต้องส่งบอลให้เพื่อนเล่นต่อง่ายๆครับ ไม่งั้นเป็นบอลชายเดี่ยว)

3. technology leveraging (0 คะแนน) => ยังไม่ได้ใช้ tech อะไรยากครับ ไม่มีคะแนนให้

4. git usage (0.5 คะแนน) => ติดไฟล์ Seller กับ SellerTest มา เพราะลืม pull master ทำให้ตัดไป 0.25 และอยากให้ commit ทีละไฟล์และทีละ action มันจะอธิบาย change ได้ดีกว่านี้ครับ

พัฒนาขึ้นจาก PR ที่แล้วพอสมควรเลยครับ พี่จะค่อยๆเสริมส่วนที่ขาดให้นะ
@iThanathat